# Generated by Django 4.1.5 on 2023-01-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todow', '0002_rename_impotant_todo_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_complated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
